/**
 * Pre-baked encryption keys for E2E shard users.
 *
 * Instead of deriving keys via Argon2id every CI run (60-180s per user),
 * keys are generated once and stored as a GitHub secret (E2E_ENCRYPTION_KEYS).
 *
 * global-setup.ts upserts the public key + salt into user_encryption_keys.
 * auth.setup.ts injects the private key into localStorage/storageState.
 *
 * Generated by: scripts/generate-e2e-keys.ts
 */

export interface PrebakedKeyData {
  email: string;
  db: {
    public_key: Record<string, unknown>;
    encryption_salt: string;
  };
  localStorage: {
    privateKeyJwk: Record<string, unknown>;
    publicKeyJwk: Record<string, unknown>;
    salt: string;
  };
}

let keysCache: Record<string, PrebakedKeyData> | null = null;

/**
 * Load pre-baked keys from E2E_ENCRYPTION_KEYS env var.
 * Returns null if not set (local dev without pre-baked keys).
 */
export function getPrebakedKeys(): Record<string, PrebakedKeyData> | null {
  if (keysCache !== null) return keysCache;

  const raw = process.env.E2E_ENCRYPTION_KEYS;
  if (!raw) return null;

  try {
    keysCache = JSON.parse(raw) as Record<string, PrebakedKeyData>;
    return keysCache;
  } catch (err) {
    console.warn('Failed to parse E2E_ENCRYPTION_KEYS:', err);
    return null;
  }
}

/**
 * Get pre-baked keys for a specific user email.
 * Returns null if pre-baked keys are not available.
 */
export function getPrebakedKeysForUser(
  email: string
): PrebakedKeyData | null {
  const allKeys = getPrebakedKeys();
  if (!allKeys) return null;
  return allKeys[email] ?? null;
}

/**
 * Check if pre-baked keys are available.
 */
export function hasPrebakedKeys(): boolean {
  return getPrebakedKeys() !== null;
}
